services:
  - type: web
    name: tiktok-traking
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-traking-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: tiktok-traking-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: tiktok-traking.onrender.com
      - key: API_KEY_GROQ
        sync: false
      - key: WHISPER_MODEL
        value: small
      - key: WHISPER_LANGUAGE
        value: fr
      - key: RISK_THRESHOLD
        value: 0.7

databases:
  - name: tiktok-traking-db
    databaseName: tiktok_traking
    user: tiktok_traking_user
    plan: free

services:
  - type: redis
    name: tiktok-traking-redis
    plan: free
    maxmemoryPolicy: noeviction
